sensio_framework_extra:
    router: { annotations: false }
    request: { converters: false, auto_convert: false }
    view: { annotations: true }
    cache: { annotations: true }
    security: { annotations: false }
    psr_message: { enabled: false }

